version: '3.8'
services:
# nest application service
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - api
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/prisma
    depends_on:
      - postgres
    restart: unless-stopped
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    networks:
      - api
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/pgadmin
    restart: unless-stopped 

# postgres service
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    env_file:
      - .env
    networks:
      - api
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
networks:
 api:
  driver: bridge
volumes:
 pgdata:
