version: '3.8'
services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - api
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/prisma
    depends_on:
      - postgres
# postgres service
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    env_file:
      - .env
    networks:
      - api
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
 api:
  driver: bridge
volumes:
 pgdata:
