version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
  nestjs-api:
    container_name: nestjs-api-c
    image: 'nestjs-api-i'
    ports:
      - '4000:4000'
    depends_on:
      - dev-db
networks:
  nestdockerservice: